OBJ=affine.o ../affinelib/affinelib.o
TARGET=affine
CFLAGS=-I../affinelib

$(TARGET): $(OBJ)
	$(CC) -o $(TARGET) $(OBJ) 

affine.o:
../affinelib/affinelib.o:
clean:
	rm -f $(TARGET) $(OBJ)
